USE GymManager;
GO
INSERT INTO ACCOUNT (Username, Password) VALUES ('nguyenvana', 'Hash_P@ssw0rd123'), 
('lethib', 'Secure!9988'), 
('tranvan_c', 'C_tran_2026!'), 
('hoang_thi_d', 'D_hoang_secret'), 
('pham_minh_e', 'MinhE_#2024'), 
('vu_thi_f', 'F_vu_secure'), 
('dang_van_g', 'G_dang_pass'), 
('bui_thi_h', 'H_bui_99@'), 
('do_van_i', 'I_do_v_2026'), 
('ngo_thi_k', 'K_ngo_k_123'),
 ('duong_van_l', 'L_duong_pass'), 
('ly_thi_m', 'M_ly_secret'), 
('phan_van_n', 'N_phan_987'), 
('truong_thi_o', 'O_truong_!@#'),
 ('trinh_van_p', 'P_trinh_2024'),
 ('ha_thi_q', 'Q_ha_secure1'), 
('cao_van_r', 'R_cao_pass12'),
 ('lam_thi_s', 'S_lam_secret!'), 
('phung_van_t', 'T_phung_2026'), 
('mai_thi_u', 'U_mai_9988');
