USE GymManager;
GO

DROP TABLE IF EXISTS WORK_OUT_PLAN;
DROP TABLE IF EXISTS PAYMENT;
DROP TABLE IF EXISTS MEMBER;
DROP TABLE IF EXISTS TRAINER;

DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS MEMBERSHIP_TYPE;
DROP TABLE IF EXISTS WORK_OUT;

GO